import { createSlice } from "@reduxjs/toolkit";

//Create slice named topic (remember: slices have a name, initalSate and reducers at a minimum)

export const topicsSlice = createSlice({
  name: "topics",
  initialState: {
    topics: {}
  },
  //expect payload to look like: {id: '123456', name: 'name of topic', icon: 'icon url'}
  reducers: {
    //adds payload at id index
    addTopic: (state, action) => {
      const { id, name, icon } = action.payload;
      state.topics[id] = {
        id: id,
        name: name,
        icon,
        quizIds: []
      };
    }
  }
});

//export addTopic action creator in the reducer
export const { addTopic } = topicsSlice.actions;
//export selector that selects topics object nested within the topics' inital state(hence topics.topics)
export const selectTopics = (state) => state.topics.topics;
//export reducer generated by createSlice
export default topicsSlice.reducer;
